name: auto-update-discord-bot
on: push
env: 
  AWS_REGION: ap-east-1
jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@v4

     - name: configure aws credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ env.AWS_REGION }}

     - name: setup-terraform
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: "1.8.2"

     - name: login to ecr
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2

     - name: Build, tag and push image to ECR
       id: build-image
       env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: discord-bot-hermes
        IMAGE_TAG: latest
       working-directory: ${{ github.workspace }}
       run: |
        docker buildx build . -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push 952800808852.dkr.ecr.ap-east-1.amazonaws.com/discord-bot-hermes:latest

     - name: initiate terraform
       run: terraform init

     - name: plan and execute terraform file
       run: |
        terraform plan
        terraform apply --auto-approve